variables:
    CONAN_USERNAME: "admin"
    CONAN_REFERENCE: "hello/0.1.0"
    CONAN_CHANNEL: "testing"
    CONAN_LOGIN_USERNAME: "admin"
    CONAN_UPLOAD: "http://185.185.69.20:8081/artifactory/api/conan/conan-local"

.build-template: &build-template
    before_script:
        - sudo pip install --upgrade conan conan_package_tools
        - conan user
    script:
        - python build.py

gcc-6:
    image: lasote/conangcc6
    variables:
        CONAN_GCC_VERSIONS: "6"
    <<: *build-template

gcc-7:
    image: lasote/conangcc7
    variables:
        CONAN_GCC_VERSIONS: "7"
    <<: *build-template

clang-4.0:
    image: lasote/conanclang40
    variables:
        CONAN_CLANG_VERSIONS: "4.0"
    <<: *build-template
