language: cpp

install:
  # Install conan
  - pip install --user -g conan
  # Automatic detection of your arch, compiler, etc.
  - conan user

script:
  - mkdir build && cd build
  - conan install .. --build
  - cmake ..
  - cmake --build .
  - ./bin/test_hello
